id = "ssh-config"
name = "SSH Config"
version = "0.2.0"
schema_version = 1
authors = ["Pranav Mangal <pranav.mangal.7@gmail.com>"]
description = "Provides syntax highlighting for SSH config files"
repository = "https://github.com/pranavmangal/zed-ssh-config"

[grammars.ssh_config]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config"
commit = "71d2693deadaca8cdc09e38ba41d2f6042da1616"
