id = "ssh-config"
name = "SSH Config"
version = "0.4.0"
schema_version = 1
authors = ["Pranav Mangal <pranav.mangal.7@gmail.com>"]
description = "Provides syntax highlighting for SSH config files"
repository = "https://github.com/pranavmangal/zed-ssh-config"

[grammars.ssh_config]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config"
commit = "0c35b243392268f48fd096607da192d76c843398"
